### ISSUE TITLE
Consider running tests in parallel by default

### ISSUE THREAD

**Issue by musicinmybrain** [pauldmccarthy/indexed_gzip#101]
If there aren’t any known reasons not to do so (filesystem race conditions, etc.), consider using [pytest-xdist](https://pypi.org/project/pytest-xdist/) to run the tests in parallel by default.

In a trial on a machine with 16 physical cores and SMP disabled, using Python 3.10.5, this sped up the overall test suite from 13m8 to 5m17s.

I can offer a simple PR if you like the idea.

One can always run tests in parallel manually, without source code changes, by ensuring `pytest-xdist` is installed and then using the `-n` argument to `pytest`, e.g. `-n auto`.

**Comment by pauldmccarthy** [comment]
Hi @musicinmybrain, I wouldn't personally benefit from this, as I leave the bulk of the tests to be run using CI (and thus parallelised across platforms/archtectures/Python versions). However, I don't think there would be any problem with this, so feel free to open a PR.

**Comment by musicinmybrain** [comment]
> Hi @musicinmybrain, I wouldn't personally benefit from this, as I leave the bulk of the tests to be run using CI (and thus parallelised across platforms/archtectures/Python versions). However, I don't think there would be any problem with this, so feel free to open a PR.

Thanks for your response!

You know, if it doesn’t benefit you and the CI is already parallelized by environment—and given how easy it is to manually run the tests in parallel—I’m inclined to say it isn’t worth adding the test dependency on `pytest-xdist` to do it upstream.

**Comment by pauldmccarthy** [comment]
@musicinmybrain No problem; but just to be clear, I have no problems with this change  if _you_ would benefit from it :)
