### ISSUE TITLE
Can't create indexes from un-seekable fileobj's

### ISSUE THREAD

**Issue by epicfaace** [pauldmccarthy/indexed_gzip#102]
It would be good to be able to create indexes from a fileobj that is un-seekable at the time of index creation. @pauldmccarthy do you think that is possible given the code, or does the code rely fundamentally on seeking somewhere to create the index?

**Comment by pauldmccarthy** [comment]
Hi @epicfaace, I don't have a problem with this - will continue the discussion at #103
