### ISSUE TITLE
is stderr expected/normal?

### ISSUE THREAD

**Issue by yarikoptic** [pauldmccarthy/indexed_gzip#11]
There is a bugreport in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901764  which points that tests produce output to stderr, which is by default a sign of trouble to autopkgtest in debian.  I just want to confirm with you that it is all Ok: here is a sample output https://ci.debian.net/data/autopkgtest/unstable/amd64/i/indexed-gzip/495403/log.gz

**Comment by pauldmccarthy** [comment]
It all looks ok to me - Cython tends to produce code that induces warnings on every platform I have used it on. I'm not enough of a Cython expert to know whether it is a cause for concern.

The `warning: unused variable ‘doff’` warning is referring to a variable that is only declared if a `ZRAN_VERBOSE` debug macro has been defined, so it seems that the warning is being incorrectly raised.

**Comment by pauldmccarthy** [comment]
Aah - I just realised that I have `-Wall -pedantic` in `setup.py`. Perhaps I should tell the compiler to relax a little :)

**Comment by pauldmccarthy** [comment]
Actually, I wouldn't mind leaving `-Wall -pedantic` in, as it applies to my own code as well - I don't think I have fine-grained enough control to set different compiler flags for cythonized versus C code.

As long as this is not a problem for you!

**Comment by yarikoptic** [comment]
I am fine with it! No worries

**Comment by yarikoptic** [comment]
Fwiw I just adjusted config to ignore stderr and we are green now https://ci.debian.net/packages/i/indexed-gzip/
