### ISSUE TITLE
Tests are shipped with the wheel

### ISSUE THREAD

**Issue by mxmlnkn** [pauldmccarthy/indexed_gzip#115]
Hello,

While analyzing the size of my AppImage, I noticed that it contains 6.9 MB MBs inside  `ctest_indexed_gzip.cpython-311-x86_64-linux-gnu.so` and 4.4 MB inside `ctest_zran.cpython-311-x86_64-linux-gnu.so`. In fact `indexed_gzip` install the whole test folder contents into `site-packages`. Was the inclusion of that folder intentional? I don't see the point of shipping it...

**Comment by pauldmccarthy** [comment]
Hi @mxmlnkn, I did this intentionally so that the tests can be run against an installation, in addition to against an in-source checkout. I've found this strategy useful in other projects for catching errors (primarily administrative/organisational).

**Comment by mxmlnkn** [comment]
Thanks for the explanation.
