### ISSUE TITLE
Tests fail with fixtures not found

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/indexed_gzip#12]
I get over [40 test failures](http://bpaste.net/show/846def09e854) which all look something like the following:

```
__________________ ERROR at setup of test_IndexedGzipFile_pread_threaded_drop_handles ___________________
file /var/tmp/portage/dev-python/indexed_gzip-0.8.7/work/indexed_gzip-0.8.7-python2_7/lib/indexed_gzip/tests/test_indexed_gzip_threading.py, line 35
  def test_IndexedGzipFile_pread_threaded_drop_handles(testfile, nelems):
E       fixture 'testfile' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/var/tmp/portage/dev-python/indexed_gzip-0.8.7/work/indexed_gzip-0.8.7-python2_7/lib/indexed_gzip/tests/test_indexed_gzip_threading.py:35
```

Am I missing some deps? The package doen't really list deps, does it? However, I see in `.travis.yaml` that you install cython? Is that needed to compile

**Comment by pauldmccarthy** [comment]
Yes - `indexed_gzip` needs Cython. Numpy is also needed to run the tests, as mentioned in the readme - I'm guessing this is why the tests are failing for you.

**Comment by TheChymera** [comment]
@pauldmccarthy sadly that can't be it (I was jsut asking so that I know what to add to the dependency list). My system, however, already has these packages installed, so it must be something else. Any idea what? what is the `testfile` fixture and what is supposed to provide it?

**Comment by pauldmccarthy** [comment]
It's a file which can be specified on the command line as a `--testfile` argument to `pytest`. If not provided it should be automatically generated. How are you invoking pytest?

**Comment by TheChymera** [comment]
@pauldmccarthy inspired by your [`run_tests.sh`](https://github.com/pauldmccarthy/indexed_gzip/blob/06bb08f035505426de622ad3865e8d33f6f5c4d3/.ci/run_tests.sh#L31):

```
export INDEXED_GZIP_TESTING=1
cd ${BUILD_DIR} || die
pytest -v -s || die
```

`python setup.py develop;` isn't really needed, since, as you can see in the log, the software already got built in the ${BUILD_DIR}.

No `testfile` is anywhere in the build directories, but there is a `compat` (though both “fixtures”) aren't found:

```
zenhost /var/tmp/portage/dev-python/indexed_gzip-0.8.7/work/indexed_gzip-0.8.7 # find -name "*testfile*"
zenhost /var/tmp/portage/dev-python/indexed_gzip-0.8.7/work/indexed_gzip-0.8.7 # find -name "*compat*"
./compat
```

**Comment by pauldmccarthy** [comment]
`testfile` is the name of the argument - the file will have a different name. It is created in a file called `conftest.py` in the root of the source tree. It looks like `pytest` is not finding this file - have you included it in your packaging? `pytest` is a bit finnicky about where `conftest.py` can be located, so I was unable to put it inside the `indexed_gzip/tests/` directory.

**Comment by TheChymera** [comment]
@pauldmccarthy ok, testing with:

```
    cp conftest.py ${BUILD_DIR}
    cd ${BUILD_DIR} || die
    pytest -v -s || die
```

did the trick. Thank you :)
