### ISSUE TITLE
Re-enable musllinux wheels

### ISSUE THREAD

**Issue by george-hopkins** [pauldmccarthy/indexed_gzip#140]
A while ago, NumPy started publishing wheels for musllinux (numpy/numpy#23069). Would it be possible to re-enable it for this package too?

**Comment by pauldmccarthy** [comment]
Hi @george-hopkins, I planned to re-enable them as part of #139, but that is blocked by some annoying Windows CI failures (which I'm fairly sure are not at all indicative of an issue with `indexed_gzip`). I'll keep plugging away at the remote debugging when I have a spare moment ..

**Comment by pauldmccarthy** [comment]
Hi @george-hopkins these should now be published - feel free to re-open this issue if you have any problems.
