### ISSUE TITLE
Missing pip install dependencies?

### ISSUE THREAD

**Issue by mxmlnkn** [pauldmccarthy/indexed_gzip#17]
First Try:

```
> pip3 install indexed_gzip
Collecting indexed_gzip
  Downloading https://files.pythonhosted.org/packages/89/44/9dba9959a240ba2e1eadb5faeb62d2e6be155507b2ebd9546a61bb44a97e/indexed_gzip-0.8.8.tar.gz (425kB)
    100% |████████████████████████████████| 430kB 2.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6czt6644/indexed-gzip/
```

Second try after `pip3 install setuptools`:

```
> pip3 install indexed_gzip
Collecting indexed_gzip
  Using cached https://files.pythonhosted.org/packages/89/44/9dba9959a240ba2e1eadb5faeb62d2e6be155507b2ebd9546a61bb44a97e/indexed_gzip-0.8.8.tar.gz
Building wheels for collected packages: indexed-gzip
  Running setup.py bdist_wheel for indexed-gzip ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mubg3tsw/indexed-gzip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpscqgftbbpip-wheel- --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for indexed-gzip
  Running setup.py clean for indexed-gzip
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mubg3tsw/indexed-gzip/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: option --all not recognized
  
  ----------------------------------------
  Failed cleaning build dir for indexed-gzip
Failed to build indexed-gzip
Installing collected packages: indexed-gzip
  Running setup.py install for indexed-gzip ... |^canceled
Operation cancelled by user
```

Third try after `pip3 install wheel`:

```
> pip3 install indexed_gzip
Collecting indexed_gzip
  Using cached https://files.pythonhosted.org/packages/89/44/9dba9959a240ba2e1eadb5faeb62d2e6be155507b2ebd9546a61bb44a97e/indexed_gzip-0.8.8.tar.gz
Building wheels for collected packages: indexed-gzip
  Running setup.py bdist_wheel for indexed-gzip ... done
  Stored in directory: /home/hypatia/.cache/pip/wheels/fd/3b/bd/1dc1ff3e19c21db578d538f0b49d7dc9cb7be03ea8c666df6f
Successfully built indexed-gzip
Installing collected packages: indexed-gzip
Successfully installed indexed-gzip-0.8.8
```

**Comment by pauldmccarthy** [comment]
Hey @mxmlnkn, can you give some details about your environment, e.g. OS, Python version, type of Python installation? Both `setuptools` and `wheel` are a standard part of any modern Python installation, in particular if you are using `conda` or `virtualenv` to  manage your Python environment. 

I can't explicitly list them as dependencies, as they are used for building/installing `indexed_gzip` - it's a chicken-and-egg problem. But because they are such fundamental libraries, this is quite common across many Python projects.

But I'm curious as to why `pip` downloaded the source version of `indexed_gzip`, rather than a pre-compiled version. Perhaps you're using Python 3.7 (which I don't yet provide binaries for)?

**Comment by mxmlnkn** [comment]
```
uname -a
    Linux pc 4.5.0-1-amd64 #1 SMP Debian 4.5.1-1 (2016-04-14) x86_64 GNU/Linux
python3 --version
   Python 3.7.2+
pip3 --version
    pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.7)
```

Yes, as you can see I used pip3 for a Python3 installation. I'm not using conda or virtualenv just the debian package manager. 

I tried to hack together a singularity container definition file to reproduce the problem but that works without problems:

```
Bootstrap: docker
From: debian:sid-slim

%post
    apt-get update
    apt-get -y install python3 python3-pip zlib1g-dev
    pip3 install indexed_gzip
```

To be built with `sudo singularity build testIndexedGzip.{sif,def}`.

Btw, as you can see for python3, as it is installed from source, it also required the zlib development files to be installed. But I guess this is vastly outside the area of pip.

So yeah, not sure but it might have only been me. Although I can't really imagine how I lost the setuptools and wheels packages. I never wrote a python package, so I just assumed it could be solved by specifying these two as dependencies. If that is not possible and other projects also don't do it, then I'll have to believe you and leave it at that.

**Comment by pauldmccarthy** [comment]
Right, so if I had provided 3.7 binaries, you would never had had this problem - I'll make them available shortly, so this hopefully won't happen again.

I also suspect that both the `setuptools` and `wheel` problems would go away if you updated `pip` (either via `pip3 install --upgrade pip` or possibly via `apt`? I don't know the "right" way to do things when using an OS package manager) before trying to install `indexed_gzip` - 9.01 is quite old, and unfortunately the Python packaging ecosystem has been a bit of a moving target over the past few years.

**Comment by pauldmccarthy** [comment]
Python 3.7 builds are now up on pypi - so if you try `pip3 install indexed_gzip`, it should now download the binaries, rather than compiling from source.

**Comment by pauldmccarthy** [comment]
@mxmlnkn I just came across this, which might make things a bit clearer: https://packaging.python.org/tutorials/installing-packages/
