### ISSUE TITLE
Performance issue with large data file and distant seek point

### ISSUE THREAD

**Issue by flegeai** [pauldmccarthy/indexed_gzip#22]
Hi, 
I am trying to use your library on very large genome sequences files (fastq.gz). My program is  extracting groups of reads from a position in the gz file. Previously, I've stored the position in a db. Thus, in my program, I open the fastq.gz file as a igzip.IndexedGzipFile, and seek directly at the position where is the group of reads I'd like to extract.  

But it appears that I can get rapidly the reads that are  at the beginning of the file, but it becomes very long when the group of reads I am looking for is at the end of the gz file. 

Is it a way to modify this behavior in order to get the same performance when  retrieving a bit of compressed file at the end than at the beginning?

Thanks a lot for your help

Fabrice Legeai

**Comment by pauldmccarthy** [comment]
Have you tried pre-generating an index, as outlined here? 

https://github.com/pauldmccarthy/indexed_gzip#index-importexport

**Comment by flegeai** [comment]
As you mentioned,  I pre-generate the index,  then it works much faster.
Thanks a lot!

Fabrice
