### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by netrix** [pauldmccarthy/indexed_gzip#24]
Please add support for Python 3.8 in `.travis.yml`

**Comment by pauldmccarthy** [comment]
Sure; I'm planning to do a 1.0.0 release at some point (a symbolic rather than functional version bump), so will add 3.8 binary builds when I get around to doing that.

**Comment by pauldmccarthy** [comment]
py38 builds are available for v1.0.0 and v1.1.0 - re-open this issue if you have problems
