### ISSUE TITLE
Problems with serialization using deepcopy

### ISSUE THREAD

**Issue by ljchang** [pauldmccarthy/indexed_gzip#28]
Hi, thanks for this interesting package. We have been having some issues with deepcopy when using your package with nibabel. Unfortunately, I haven't spent much time trying to figure out why, but just wanted to raise this issue in case anyone else has been experiencing this in other contexts.  Here is an issue from our package with a little bit more information https://github.com/cosanlab/nltools/issues/281.

**Comment by pauldmccarthy** [comment]
Have you tried using a more recent version of nibabel? There was a bug related to closing file handles which was fixed in 2.3.1

**Comment by ljchang** [comment]
Thanks for looking into this. I'm currently using nibabel==3.0.2. Definitely interested in potentially being able to use this package, but no rush. Thanks!

**Comment by pauldmccarthy** [comment]
@ljchang hopefully this should be resolved in v1.1.0 (just uploaded to pypi, on conda-forge soon) - please re-open this issue if you still have problems
