### ISSUE TITLE
Win64 seek error on offsets larger than 32bit

### ISSUE THREAD

**Issue by DarioDaF** [pauldmccarthy/indexed_gzip#29]
I used this library to access a big .tar.gz backup I have.

The file is fully indexed, I use windows 10 and CPython 3.8.0 (with static zlib from https://github.com/kiyolee/zlib-win-build.git).

The error is only on Windows, if I run it on linux with the same package (fresh install from pip 2020-04-09) it works.

The error is:
> OSError: Raw stream returned invalid position -484060160
While seeking to 81120318464.

I suppose it is an overflow in the actual position since
`hex(81120318464 + 484060160) = 0x13 0000 0000`
And the same happens with another file (with sum equal to 0x9 0000 0000).

I couldn't find any problem in the source (_lseeki64 and int64_t are used everywhere).
It might be a problem with my zlib compilation, if you need more information you can send me a debug build of the wheel (or how to compile it) and I can test it.

Compressed file size: ~40 GB
Creation: `igz = indexed_gzip.IndexedGzipFile('workspace/workspace.tar.gz',  index_file='workspace/workspace.tar.gzidx')`
Usage: `t = tarfile.TarFile(fileobj = igz); t.fileobj.seek(pos)`

![TestIdxGZ](https://user-images.githubusercontent.com/10617344/78879979-f7b69100-7a54-11ea-9b32-0e832945975a.png)
Screenshot with windows execution and linux subsystem execution yielding different results.

Thanks again for this library, this backup used to take 1/2 min. just to see the file structure, now it takes ~5s to load the index and any file extraction is realy fast!

**Comment by pauldmccarthy** [comment]
Well spotted on the position+offset pattern - this does suggest an overflow. Do you happen to know the exact uncompressed (and compressed) sizes of your two files?

Unfortunately I don't have much time to track down Windows bugs - I don't have a physical machine, so have to debug remotely and non-interactively on appveyor, which is a slow and painful process. But I'll try and find some time to look into it.

**Comment by DarioDaF** [comment]
Today I found the culprit, I enabled debugging and added print statements:

` # C log
Read succeeded - 1048576 bytes read [compressed offset: 1048586]
zran_seek(37856184832, 0)
_zran_get_point_with_expand(37856184832, 0, autobuild=1)
_zran_get_point_at(37856184832, c=0)
DF: tying to call FSEEK(@, 24846135507, SEEK_SET)
DF END: called FSEEK(@, 24846135507, SEEK_SET)
`

` # Pyx log
DEBUG:indexed_gzip.indexed_gzip:_IndexedGzipFile.__init__(None, workspace/workspace.tar.gz, True, 4194304, 32768, 1048576, True)
DEBUG:indexed_gzip.indexed_gzip:_IndexedGzipFile.import_index(workspace/workspace.tar.gzidx, <_io.BufferedReader name='workspace/workspace.tar.gzidx'>)
DEBUG:indexed_gzip.indexed_gzip:_IndexedGzipFile.seek(-798520832)
`

So it seems that `self.tell()` returns a negative number…
Which is impossible, uncmp_offset is unsigned 64 bit!

`
def tell(self):
        """Returns the current seek offset into the uncompressed data stream.
        """
        return zran.zran_tell(&self.index)
/* Return the current seek position in the uncompressed data stream. */
long zran_tell(zran_index_t *index) {

    return index->uncmp_seek_offset;
}
`

but the cast to long in windows 64 Microsoft compiler used by cpython for my computer is 32bit signed, so I changed the signatrue of zrand_tell to uint64_t.

I found some posts pointing that in some versions of python this problem is present in tell (seek does not do that although.

Doing this change I found some warnings about printf signatures and casts, so I'll check them later to see if they are due to this change.

**Comment by pauldmccarthy** [comment]
aah, nice work! I think I originally had `zran_tell` return `long` because the Linux `ftell` function returns `long`. 

But this shows my lack of experience with/consideration for non-UNIX platforms.

Thanks for the PR - I'll try and spare a few hours over the next couple of days to sort out a new release.

**Comment by pauldmccarthy** [comment]
@DarioDaF Thanks again for your help - I've just uploaded v1.1.0 to pypi (and it will be on conda-forge soon) - please let me know if you have any more trouble.
