### ISSUE TITLE
zran read performance or inflate performance

### ISSUE THREAD

**Issue by lmdu** [pauldmccarthy/indexed_gzip#33]
Hi, I have used your project to develop pyfastx. It's a nice tool. In my case, I need to do large numbers of seeks for random access to content from super large gzipped file (~20Gb). However, when use zran_read to read file, it was slow. I have test the source code and found inflate consumed 0.01s per task. When we do 100000 seek/reads, that may be a long time. 

The code consumed more time was shown in below:

```
if (inflate_stop_at_block(flags)) z_ret = inflate(strm, Z_BLOCK);
else                              z_ret = inflate(strm, Z_NO_FLUSH););
```

Do you have any suggestions to improve the speed?

**Comment by pauldmccarthy** [comment]
The zip `inflate` function is performing the actual decompression, so there is not much that can be done if it is the bottleneck. 

If `inflate` is being called many times, the one thing you could try is to increase the size of the read buffer (where compressed data is read into from the file - the `readbuf_size` parameter to `zran_init`), and/or increasing the size of your own read buffer - i.e. the size of the buffer you pass to `zran_read`. 

I can't suggest specific values to use, as they are specific to the type of data you are working with (specifically the compressed / uncompressed size ratio).

**Comment by lmdu** [comment]
Thank you for your reply! I used multiprocessing module to start multiple processes to read content from gzipped file simultaneously. For large amounts of seeks and reads, this can reduce much time for large file.

**Comment by pauldmccarthy** [comment]
@lmdu feel free to re-open this if you think there is a problem with indexed_gzip.
