### ISSUE TITLE
indexed_gzip error when loading data from nibabel

### ISSUE THREAD

**Issue by pauldmccarthy** [pauldmccarthy/indexed_gzip#38]
As of `indexed_gzip` 1.3.0, this code:

```
import nibabel as nib
import numpy as np

img = nib.load('some_image.nii.gz')
data = np.asanyarray(img.dataobj)
```

results in this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paulmc/venvs/fsleyes.py37.gtk3.venv/lib/python3.7/site-packages/numpy/core/_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home/paulmc/venvs/fsleyes.py37.gtk3.venv/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 393, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/home/paulmc/venvs/fsleyes.py37.gtk3.venv/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 360, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/home/paulmc/venvs/fsleyes.py37.gtk3.venv/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 339, in _get_unscaled
    mmap=self._mmap)
  File "/home/paulmc/venvs/fsleyes.py37.gtk3.venv/lib/python3.7/site-packages/nibabel/volumeutils.py", line 508, in array_from_file
    offset=offset)
  File "/home/paulmc/venvs/fsleyes.py37.gtk3.venv/lib/python3.7/site-packages/numpy/core/memmap.py", line 228, in __new__
    fid.seek(0, 2)
  File "indexed_gzip/indexed_gzip.pyx", line 460, in indexed_gzip.indexed_gzip._IndexedGzipFile.seek
indexed_gzip.indexed_gzip.NotCoveredError: Index must be completely built in order to seek from SEEK_END
```

This is due to some [slightly dubious logic](https://github.com/nipy/nibabel/blob/8ed5f746a8973946778eef324b6a0bf538beb7d0/nibabel/volumeutils.py#L501) in `nibabel` - it blindly attempts to memory-map an open file object, and silently falls back to file-based random access if the memory map attempt raises one of a fixed set of error types. 

`indexed_gzip` previously raised a `ValueError` on attempts to seek from `SEEK_END`, but I changed it to raise a `NotCoveredError`. This is because  `SEEK_END` is now possible, but only if the file is fully covered by the index, so I thought that changing the error type to `NotCoveredError` semantically made sense.

Philosophically, I think the "correct" solution here would be to patch `nibabel` so that it considers the `IndexedGzipFile` file object to be a [compresed file type](https://github.com/nipy/nibabel/blob/8ed5f746a8973946778eef324b6a0bf538beb7d0/nibabel/volumeutils.py#L40). In this case, `nibabel` will skip the mem-map attempt entirely, and use file-based access.

But I have admittedly broken semver principles by changing the error type - this really does equate to an API change. And I can release much more quickly than nibabel can, so I'll cut a new `indexed_gzip` release which reverts this change, so that the error type is `ValueError`, which will cause the attempt by `nibabel` to mem-map the file to silently fail, and cause it to revert to file-based access.

@mathieuboudreau @Stoyan-I-A, thanks for bringing this to my attention.

**Comment by effigies** [comment]
Is it reasonable to subclass `NotCoveredError` from `ValueError`? As I type it, though, it does seem semantically dubious...

**Comment by pauldmccarthy** [comment]
@effigies It's easy to get caught up in semantics, isn't it :)

If `nibabel` were to recognise `IndexedGzipFile` objects as compressed files, then this error would never happen. But I really shouldn't have changed the error type either.

I think that reverting to `ValueError`, combined with patching `nibabel`, is the way to go. The former will fix the situation for users of the current version of niabel, and the latter will make this a non-issue for users of future versions of nibabel.

I will leave changing the error type back to `NotCoveredError` until `indexed_gzip` 2.x is released (if or when that ever happens, which will probably be never ... unless somebody wants to add write support, that is).

**Comment by pauldmccarthy** [comment]
CI is unfortunately quite slow, but hopefully a new version will be up on PyPI by the end of today*

*intentionally not specifying the time zone. Let's go with Hawaii.
