### ISSUE TITLE
Plans for Python 2.7 support

### ISSUE THREAD

**Issue by effigies** [pauldmccarthy/indexed_gzip#41]
Hi Paul,

Just want to get a sense of what your plans are for maintaining Python 2.7 support. Knowing this can help set version constraints on nibabel's legacy (2.5.x) series.

**Comment by pauldmccarthy** [comment]
Hey Chris, I don't really have any plans for this project - it's basically in maintenance mode, and the Python side of the code is quite small and easy to maintain. So at this point in time I don't see any need to remove Python 2.7 support.
