### ISSUE TITLE
Missing zlib.dll

### ISSUE THREAD

**Issue by zvasicek** [pauldmccarthy/indexed_gzip#43]
I tried this library on Windows but zlib.dll is missing when installed via pip. Tested with 64-bit Python v3.8. It would be great if you could link the zlib library statically and remove this dependency. It is not easy to find the latest version of zlib for 64-bit system. Thank you

**Comment by pauldmccarthy** [comment]
I don't feel particularly strongly about this, but to be honest, I am erring on the side of leaving things the way they are - `indexed_gzip` is designed as a replacement for the built-in Python `gzip` library, and even the latter won't work if you don't have `zlib` installed. 

You might want to consider using conda, which makes it very easy to install non-Python dependencies.

**Comment by pauldmccarthy** [comment]
As part of migrating from appveyor/travis to github actions, I updated the Windows build procedure to compile the zlib sources in as part of the Windows binary wheels. So for `indexed_gzip` 1.4.0, `zlib` should no longer be required in order to use `indexed_gzip`.
