### ISSUE TITLE
ARM64 builds?

### ISSUE THREAD

**Issue by effigies** [pauldmccarthy/indexed_gzip#44]
Hi Paul, I was just curious if there's any plan to build ARM64 (and other) wheels. Travis now [supports](https://docs.travis-ci.com/user/multi-cpu-architectures/) other architectures, so I'm adding support for those as numpy wheels come online, and it would be nice to get indexed-gzip tests running on those, if that's something you're interested in.

**Comment by pauldmccarthy** [comment]
Hey @effigies I seem to remember having trouble with ARM a while back, although can't remember what that trouble was, nor why I was trying to compile for ARM. But I'm happy to look into it again - will try and remember to have play over the next couple of weeks.

**Comment by smilerish** [comment]
Hi, I'm wondering if this is related. I've 'successfully' built indexed-gzip from source on a Raspberry Pi (ARM v7h) but it doesn't appear to be working when called from [ratarmount](https://github.com/mxmlnkn/ratarmount). I get many warnings when compiling, most of them being `ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]`, but no errors. I also get no runtime errors, but ratarmount does not behave as expected (it doesn't actually generate a gzip index).

I tried the test suite on 1.4.0, which passes with 20 warnings:
- 14 x `PytestUnknownMarkWarning`
- 4 x `DeprecationWarning: tostring() is deprecated. Use tobytes() instead`
- 2 x `PytestCacheWarning: could not create cache path`

The test environment: `platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1`

Then I tried 1.5.2, which failed with 18 errors and 22 warnings. 1.5.2 seems to have more tests, and it fails some pretty fundamental ones!
- `zran_seek returned error: -1`
- lots of assertion errors, which seem to be seek related, too.

Is there anything I can try or provide to help with debugging this? I'm very much a novice coder, but happy to try debug builds, share logs, outputs, etc.

**Comment by pauldmccarthy** [comment]
Hi @smilerish, I'm afraid I won't be able to provide official armv7 builds at the moment, but I am hoping to add arm64 builds in the next release. 

I have made some changes on the `mnt/32bit` branch - is there any chance you could try that version?

**Comment by pauldmccarthy** [comment]
@effigies It only took me 6 months, but ARM64 (`aarch64`) builds are now up on PyPi!

@smilerish The changes I mentioned have been released in version 1.5.3 - would you be able to try that out?

**Comment by effigies** [comment]
Nice! Unfortunately, TravisCI did stop running our builds a while back... I've asked them to put nipy on a open source plan, so we can see if we can start testing again.

**Comment by pauldmccarthy** [comment]
@effigies You might be able to knock something up in GHA using the [`docker/setup-qemu-action`](https://github.com/marketplace/actions/docker-setup-qemu)  - i.e. install qemu, then run your tests with your ARM docker image of choice. It was easy for me, because [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) does all the hard work!

**Comment by smilerish** [comment]
> @smilerish The changes I mentioned have been released in version 1.5.3 - would you be able to try that out?

I'll give it a go! It's okay, I wasn't looking for builds, just debugging the code so a local build works. I'll let you know how it goes!

**Comment by effigies** [comment]
Just checked back in and `indexed_gzip` is getting installed on our aarch64 CI builds.
