### ISSUE TITLE
Closing files between reads

### ISSUE THREAD

**Issue by effigies** [pauldmccarthy/indexed_gzip#5]
The main thing that's important about `indexed_gzip` is a persistent index. Would it possible to (at least optionally) move to a model in which the file is opened at the beginning of read calls and closed at the end?

This would go some way toward making it a more comfortable drop-in for nibabel. (I suspect some of what we've been seeing over at fmriprep has been filehandle exhaustion appearing as `MemoryError`s.)

**Comment by pauldmccarthy** [comment]
This is a good idea, and I'm not sure why I didn't build this into the design from the beginning. I will have a play around with #6 to see if it breaks any of the tests. Thanks!
