### ISSUE TITLE
Can't install vcpython27

### ISSUE THREAD

**Issue by epicfaace** [pauldmccarthy/indexed_gzip#71]
The script install_vcpython27.sh is failing now with the following error:

It seems that Microsoft removed support for this package in April 2021 and it's been deprecated from Chocolatey. See https://github.com/joerick/cibuildwheel/pull/649 and https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27.

I guess we might have to stop building wheels for Windows on Python 2.7, or maybe use a workaround.

**Comment by pauldmccarthy** [comment]
Thanks for the info - I'm inclined to drop support, and add it back in if anybody complains vehemently ..
