### ISSUE TITLE
Add filename to exception messages, when known

### ISSUE THREAD

**Issue by effigies** [pauldmccarthy/indexed_gzip#81]
It would be helpful for debugging issues to quickly identify the file that produced an error. Would it be possible for `indexed-gzip` to add the filename to exception messages when `_IndexedGzipFile.filename is not None`?

**Comment by pauldmccarthy** [comment]
Hi @effigies, that sounds like a perfectly reasonable thing to do - I should be able to have a patch release out later today..

**Comment by pauldmccarthy** [comment]
Are there any specific exceptions you'd like covered, in addition to the ones in #84?

**Comment by effigies** [comment]
Thanks! The main ones I've encountered are covered. Left a small note over in #84.
