### ISSUE TITLE
Relax mode check

### ISSUE THREAD

**Issue by mxmlnkn** [pauldmccarthy/indexed_gzip#85]
Hi,

I love the newly added support for Python file-like objects!

I'm currently trying to use that with a file-object returned by `zipfile`, however, I found that `zipfile` only supports `r` and `w` modes but `indexed_gzip` checks that the mode is exactly `rb`. Would it be possible to relax that mode check to also accept `r`? I only see problems if it was something like `rt` or `w` but I'm not sure what the conventions are for file modes in Python. Maybe the zipfile module is wrong for not setting the mode to `rb`. Currently, I'm circumventing this by overwriting the `mode` member manually before forwarding the file object to `indexed_gzip`.

Also, I noticed that the check does not work when specifying the file object as the first argument (the `filename` one). This is because the mode check is done before `filename` is checked whether it is a file object.

Steps to reproduce:

1. Create test file:

```bash
echo foo > bar
gzip -k bar
7z a bar.zip bar.gz
```

2. Try to resolve both compressions through Python:

```python3
import indexed_gzip
import zipfile
zip = zipfile.ZipFile("bar.zip")  # argument: mode='rb' won't work
file = zip.open("bar.gz")
# file.mode='rb'  # Kinda hacky but should work for a while to circumvent the mode check
gz = indexed_gzip.open(fileobj=file)
```

Edit: Actually mypy complains about that hack: `error: Property "mode" defined in "IO" is read-only`, so this is more pressing to me.

**Comment by pauldmccarthy** [comment]
Hi @mxmlnkn, hmm, annoying - it seems that the `zipfile` module uses a different convention than the built-in `open` function - for the latter, `'r'` is equivalent to `'rt'`, whereas for a `ZipFile`, and files opened via `ZipFile.open`, `'r'` is equal to `'rb'`.  So it's not possible to use `fileobj.mode` to distinguish between a text or binary stream. I'd have to use `fileobj.peek` or something, but I doubt that `peek` is available on *all* file-likes, and suspect that there's probably no reliable method to determine whether a file-like is text or binary without actually reading some data (which I don't want to do).

But I don't really see the harm in adjusting `indexed_gzip` thoug -  `mode` parameter accepts `'r'` or `'rb'`, so it makes sense to apply the same check to `fileobj.mode`.

**Comment by mxmlnkn** [comment]
So it really is zipfile, which is wrong here :/. Thank you for still accounting for that edge case. I agree that peek might not always be available. It might be even better to use a combination of read and then seek back to the previous offset but as you said it might not be worth for a simple argument check.
