### ISSUE TITLE
Can't install on Fedora

### ISSUE THREAD

**Issue by moceap** [pauldmccarthy/indexed_gzip#88]
[moceap@mosaab-pc ~]$ sudo pip3 install indexed-gzip
[sudo] password for moceap: 
Collecting indexed-gzip
  Using cached indexed_gzip-1.6.4.tar.gz (73 kB)
Building wheels for collected packages: indexed-gzip
  Building wheel for indexed-gzip (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pxhpod4f
       cwd: /tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/
  Complete output (29 lines):
  indexed_gzip setup
    have_cython: False (if True, modules will be cythonized, otherwise pre-cythonized C files are assumed to be present)
    have_numpy:  True (if True, test modules will be compiled)
    ZLIB_HOME:   None (if set, ZLIB sources are compiled into the indexed_gzip extension)
    testing:     False (if True, code will be compiled with line tracing enabled)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/indexed_gzip
  copying indexed_gzip/__init__.py -> build/lib.linux-x86_64-3.10/indexed_gzip
  creating build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/test_zran.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/test_nibabel_integration.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/test_indexed_gzip_threading.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/test_indexed_gzip.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/conftest.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/benchmark.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/__main__.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  copying indexed_gzip/tests/__init__.py -> build/lib.linux-x86_64-3.10/indexed_gzip/tests
  running build_ext
  building 'indexed_gzip.indexed_gzip' extension
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/indexed_gzip
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Iindexed_gzip -I/usr/lib64/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c indexed_gzip/indexed_gzip.c -o build/temp.linux-x86_64-3.10/indexed_gzip/indexed_gzip.o -Wall -Wno-unused-function
  cc1: fatal error: indexed_gzip/indexed_gzip.c: No such file or directory
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for indexed-gzip
  Running setup.py clean for indexed-gzip
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5
  Complete output (11 lines):
  indexed_gzip setup
    have_cython: False (if True, modules will be cythonized, otherwise pre-cythonized C files are assumed to be present)
    have_numpy:  True (if True, test modules will be compiled)
    ZLIB_HOME:   None (if set, ZLIB sources are compiled into the indexed_gzip extension)
    testing:     False (if True, code will be compiled with line tracing enabled)
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: option --all not recognized
  ----------------------------------------
  ERROR: Failed cleaning build dir for indexed-gzip
Failed to build indexed-gzip
Installing collected packages: indexed-gzip
    Running setup.py install for indexed-gzip ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-htykpj6h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/indexed-gzip
         cwd: /tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/
    Complete output (14 lines):
    indexed_gzip setup
      have_cython: False (if True, modules will be cythonized, otherwise pre-cythonized C files are assumed to be present)
      have_numpy:  True (if True, test modules will be compiled)
      ZLIB_HOME:   None (if set, ZLIB sources are compiled into the indexed_gzip extension)
      testing:     False (if True, code will be compiled with line tracing enabled)
    running install
    running build
    running build_py
    running build_ext
    building 'indexed_gzip.indexed_gzip' extension
    gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Iindexed_gzip -I/usr/lib64/python3.10/site-packages/numpy/core/include -I/usr/include/python3.10 -c indexed_gzip/indexed_gzip.c -o build/temp.linux-x86_64-3.10/indexed_gzip/indexed_gzip.o -Wall -Wno-unused-function
    cc1: fatal error: indexed_gzip/indexed_gzip.c: No such file or directory
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_huup3r1/indexed-gzip_f619728ff0d34177b3a944250e9e33c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-htykpj6h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/indexed-gzip Check the logs for full command output.
[moceap@mosaab-pc ~]$

**Comment by moceap** [comment]
I can install it by:

sudo dnf install python-indexed_gzip

So, the needed now to fix PIP installer.

**Comment by pauldmccarthy** [comment]
Hi @moceap , I haven't released binaries for Python 3.10 yet. In the meantime, to compile indexed_gzip on your machine you will need to have cython (and a C compiler toolchain) installed.

**Comment by pauldmccarthy** [comment]
Wheels are now available for python 3.10
